//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto
    {
        public int ID_FOTO { get; set; }
        public byte[] IMAGEN { get; set; }
        public int ID_GALERIA { get; set; }
    
        public virtual Galeria Galeria { get; set; }
    }
}
