//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto
    {
        public int ID_FOTO { get; set; }
        public byte[] IMAGEN { get; set; }
        public int ID_GALERIA { get; set; }
    
        public virtual Galeria Galeria { get; set; }
    }
}
