//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galeria
    {
        public Galeria()
        {
            this.Foto = new HashSet<Foto>();
        }
    
        public int ID_GALERIA { get; set; }
        public string NOMBRE { get; set; }
        public string CORREO { get; set; }
    
        public virtual ICollection<Foto> Foto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
