//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galeria
    {
        public Galeria()
        {
            this.Foto = new HashSet<Foto>();
        }
    
        public int ID_GALERIA { get; set; }
        public string NOMBRE { get; set; }
        public string CORREO { get; set; }
    
        public virtual ICollection<Foto> Foto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
